### ISSUE TITLE
Where is other imports?

### ISSUE THREAD

**Issue by tegg89** [gittykhirbat/BioNLP2016#1]
Hi, I am trying to run your sources, but I think, some import files are missing.
I downloaded train and test data from BioNLP2016 SeeDev websites.
While running classifier.py, graphKernel function in corenlpparse.py and sdpKernel file are missing.
How can I find or create these files?

**Comment by gittykhirbat** [comment]
Hi tegg,

We have moved an updated version here: https://github.com/unimelbbionlp/BioNLPST2016/
Could you please try out that?
This repo was meant to be a beta version for the developers of this project. The aforementioned repo is the official code release. I will be taking down this repo to avoid any further confusions. 

Thanks for bringing this to my attention and apologies for the inconvenience.
